version: "3.5"

services:
  plant-guilds:
    image: eldelto/plant-guilds:latest
    networks:
      - plant-guilds_net
      - caddy_net
    expose:
      - 8080
    restart: always

networks:
  plant-guilds_net:
  caddy_net:
    name: caddy_net
    external: true
